
CREATE TABLE MUSICAS
(
    CODIGO INT IDENTITY(1,1) PRIMARY KEY,
    TITULO VARCHAR(255) NOT NULL,
    CANTOR VARCHAR(255) NOT NULL,
    ESTILO VARCHAR(255) NOT NULL,
    PRECO FLOAT,
    DURACAO INT NOT NULL
);

INSERT INTO 
MUSICAS
    (TITULO,CANTOR,ESTILO,PRECO,DURACAO)
VALUES
    ('TITULO 1.1', 'CANTOR 1', 'ESTILO 1', 3.5, 240),
    ('TITULO 1.2', 'CANTOR 1', 'ESTILO 1', 2.0, 150),
    ('TITULO 1.3', 'CANTOR 1', 'ESTILO 1', 2.5, 180),
    ('TITULO 2.1', 'CANTOR 2', 'ESTILO 1', 5.0, 360),
    ('TITULO 2.2', 'CANTOR 2', 'ESTILO 1', 3.5, 240),
    ('TITULO 2.3', 'CANTOR 2', 'ESTILO 1', 2.0, 150),
    ('TITULO 3.1', 'CANTOR 3', 'ESTILO 2', 2.5, 180),
    ('TITULO 3.2', 'CANTOR 3', 'ESTILO 2', 5.0, 360),
    ('TITULO 3.3', 'CANTOR 3', 'ESTILO 2', 3.5, 240),
    ('TITULO 4.1', 'CANTOR 4', 'ESTILO 2', 2.0, 150),
    ('TITULO 4.2', 'CANTOR 4', 'ESTILO 2', 2.5, 180),
    ('TITULO 4.3', 'CANTOR 4', 'ESTILO 2', 5.0, 360);

SELECT * FROM MUSICAS WHERE TITULO = '?';
SELECT * FROM MUSICAS WHERE CANTOR = '?';
SELECT * FROM MUSICAS WHERE ESTILO = '?';
    
SELECT * FROM MUSICAS WHERE TITULO LIKE '%?%';
SELECT * FROM MUSICAS WHERE CANTOR LIKE '%?%';
SELECT * FROM MUSICAS WHERE ESTILO LIKE '%?%';

SELECT * FROM 
MUSICAS 
WHERE (:titulo IS NULL OR :titulo = '' OR TITULO = :titulo)
AND (:cantor IS NULL OR :cantor = '' OR CANTOR = :cantor)
AND (:estilo IS NULL OR :estilo = '' OR ESTILO = :estilo)
